# -*- coding: utf-8 -*-
"""
Created on Sun Jan 27 22:59:44 2019

@author: hecongcong
"""

'''
The problem 389:Find the difference
Given two string s and t which consist of only lowercase letters.
string t is generated by random shufling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:'e'
Explanation:'e' is the letter that was added.
'''


'''
The answer:本题是给定两个只包含小写字母的字符串s和t,其中t是由s随机排列，然后在随机一个位置加上一个字母产生.
本题是要找出那个加入的字母.本题可有两种解法，如下.

解法1：
1.构造一个字典dic,然后循环s，统计其中的元素和其个数的映射.
2.然后循环t,当其中的元素不在dic中或者dic[i]==0时，则返回相应元素，即为所求;
否则，相应键值减一.

解法2：
1.将s变为字符串列表lst_s.
2.循环t，如果其中的元素不在lst_s中，则返回相应元素，否则从lst_s中将其移除.

代码如下.
'''
#解法1
class Solution:
    def findTheDifference(self,s,t):
        dic={}
        for i in s:
            if(i not in dic):
                dic[i]=1
            else:
                dic[i]+=1
        for i in t:
            if(i not in dic or dic[i]==0):
                return(i)
            else:
                dic[i]-=1


#解法2
class Solution:
    def findTheDifference(self,s,t):
        lst_s=list(s)
        for i in t:
            if(i not in lst_s):
                return(i)
            else:
                lst_s.remove(i)
                

            
    
    
   
